version: "3.8"
services:
  router:
    build:
      context: .
      dockerfile: ./build/Dockerfile.router
    image: public.ecr.aws/zebrunner/router:2.1.6
    env_file:
      - router.env
    ports:
        - "4444-4445:4444"
    links:
      - redis
      - db
#    volumes:
#      - "${HOME}/.aws:/root/.aws"
    logging:
     options:
      max-size: "512m"
    restart: always
  scaler:
    container_name: scaler
    build:
      context: .
      dockerfile: build/Dockerfile.scaler
    image: public.ecr.aws/zebrunner/scaler:2.1.6
    env_file:
      - scaler.env
    links:
      - redis
#    volumes:
#      - "${HOME}/.aws:/root/.aws"
    restart: always
  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - "pgdata-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:6
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
volumes:
  pgdata-volume:
