version: "3.8"
services: 
  grid:
    build:
      context: .
      dockerfile: ./build/Dockerfile.server
    ports: 
        - "4444-4445:4444"
    volumes:
      - "${HOME}/.aws:/root/.aws"
    links:
      - redis
      - db
    depends_on:
      - management
    command: ./scripts/entrypoint.sh
    logging:
     options:
      max-size: "512m"
    restart: always
  management:
    container_name: esg-worker
    build:
      context: .
      dockerfile: ./build/Dockerfile.worker
    volumes:
      - "${HOME}/.aws:/root/.aws"
    links:
      - redis
    command:
      - ./scripts/worker_entrypoint.sh
    restart: always
  db:
    image: postgres:13
    container_name: esg-postgres
    volumes:
      - "pgdata-volume:/var/lib/postgresql/data"
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always
  redis:
    image: redis:6
    container_name: esg-redis
    ports:
      - "6379:6379"
    restart: always
volumes:
  pgdata-volume:
