// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: definitions.proto

package definitions

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Service_GetTaskDefinitionRevision_FullMethodName       = "/definitions.Service/getTaskDefinitionRevision"
	Service_GetTaskDefinitionRevisionByHash_FullMethodName = "/definitions.Service/getTaskDefinitionRevisionByHash"
	Service_GetImages_FullMethodName                       = "/definitions.Service/getImages"
)

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	// todo add cache support for this method
	// create definition according to the  environment.Environment and return revision id
	// for generic tasks
	GetTaskDefinitionRevision(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*Revision, error)
	// get revision by hash (without explicit reference to redis)
	GetTaskDefinitionRevisionByHash(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*Revision, error)
	// get images list from ecr (public and private)
	GetImages(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) GetTaskDefinitionRevision(ctx context.Context, in *Configuration, opts ...grpc.CallOption) (*Revision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Revision)
	err := c.cc.Invoke(ctx, Service_GetTaskDefinitionRevision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetTaskDefinitionRevisionByHash(ctx context.Context, in *Hash, opts ...grpc.CallOption) (*Revision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Revision)
	err := c.cc.Invoke(ctx, Service_GetTaskDefinitionRevisionByHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetImages(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Image], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Service_ServiceDesc.Streams[0], Service_GetImages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, Image]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_GetImagesClient = grpc.ServerStreamingClient[Image]

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility.
type ServiceServer interface {
	// todo add cache support for this method
	// create definition according to the  environment.Environment and return revision id
	// for generic tasks
	GetTaskDefinitionRevision(context.Context, *Configuration) (*Revision, error)
	// get revision by hash (without explicit reference to redis)
	GetTaskDefinitionRevisionByHash(context.Context, *Hash) (*Revision, error)
	// get images list from ecr (public and private)
	GetImages(*emptypb.Empty, grpc.ServerStreamingServer[Image]) error
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceServer struct{}

func (UnimplementedServiceServer) GetTaskDefinitionRevision(context.Context, *Configuration) (*Revision, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskDefinitionRevision not implemented")
}
func (UnimplementedServiceServer) GetTaskDefinitionRevisionByHash(context.Context, *Hash) (*Revision, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskDefinitionRevisionByHash not implemented")
}
func (UnimplementedServiceServer) GetImages(*emptypb.Empty, grpc.ServerStreamingServer[Image]) error {
	return status.Errorf(codes.Unimplemented, "method GetImages not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}
func (UnimplementedServiceServer) testEmbeddedByValue()                 {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_GetTaskDefinitionRevision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Configuration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetTaskDefinitionRevision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetTaskDefinitionRevision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetTaskDefinitionRevision(ctx, req.(*Configuration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetTaskDefinitionRevisionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Hash)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetTaskDefinitionRevisionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Service_GetTaskDefinitionRevisionByHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetTaskDefinitionRevisionByHash(ctx, req.(*Hash))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ServiceServer).GetImages(m, &grpc.GenericServerStream[emptypb.Empty, Image]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Service_GetImagesServer = grpc.ServerStreamingServer[Image]

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "definitions.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getTaskDefinitionRevision",
			Handler:    _Service_GetTaskDefinitionRevision_Handler,
		},
		{
			MethodName: "getTaskDefinitionRevisionByHash",
			Handler:    _Service_GetTaskDefinitionRevisionByHash_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getImages",
			Handler:       _Service_GetImages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "definitions.proto",
}
