FROM alpine:latest

RUN apk add -U ca-certificates tzdata curl && rm -Rf /var/cache/apk/*

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz | tar -xvz
RUN cp migrate.linux-amd64 /usr/bin/migrate

COPY ./migrations/ /migrations/

CMD migrate -path migrations -database postgres://postgres:postgres@db/postgres?sslmode=disable up
# CMD migrate -path migrations -database postgres://postgres:postgres@db/postgres?sslmode=disable down -all
