syntax = "proto3";
package definitions;

option go_package = "./definitions";

import "google/protobuf/empty.proto";

service Service {

    // todo add cache support for this method
    // create definition according to the  environment.Environment and return revision id
    // for generic tasks
    rpc getTaskDefinitionRevision(Configuration) returns (Revision);

    // get revision by hash (without explicit reference to redis)
    rpc getTaskDefinitionRevisionByHash(Hash) returns (Revision);

    // get images list from ecr (public and private)
    rpc getImages(google.protobuf.Empty) returns (stream Image);
}

message Configuration {
    // configuration should be json-marshalled environment.Environment object
    //todo think about another options how send no-proto message
    bytes configuration = 1;
}

message Revision {
    int64 value = 1;
}

message Hash {
    string value = 1;
}

message Image {
	string name = 1;
	string version = 2;
	string platform =3;
	string browserName = 4;
	string browserVersion = 5;
	// TODO: investigate possibility of 'ImageUrl' field removal
	string imageUrl = 6 [json_name="image"];
}
